Updated tiammat command to check for all executables in path. Updated shebang of python scripts to call env.

diff --git a/tiammat b/tiammat
--- a/tiammat
+++ b/tiammat
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 # LOADING PROGRAM PATHS AS VARIABLES #
 
@@ -11,12 +11,77 @@ HMMSEARCH=`which hmmsearch`
 HMMALIGN=`which hmmalign`
 HMMBUILD=`which hmmbuild`
 HMMPRESS=`which hmmpress`
-HMMSCAN=`which hmmscan`
+HMMSCAN=`which hmmscan` 
 
 # Script command variables:
 PULL_COORDINATES=`which Pull_coordinates.py`
 SELECT_CONTIGS=`which select_contigs.pl`
 BEST_FIT_DOMAINS=`which Best_fit_domains.py`
+
+######################################
+
+# Check commands are all executable
+EXECUTABLE_ERROR=`echo "FALSE"`
+
+if ! [[ -x $HMMSEARCH ]]; then
+        EXECUTABLE_ERROR=`echo "TRUE"`
+        printf "\nERROR: Cannot find hmmsearch executable in \$PATH...\n"
+fi
+
+if ! [[ -x $HMMALIGN ]]; then
+        EXECUTABLE_ERROR=`echo "TRUE"`
+        printf "\nERROR: Cannot find hmmalign executable in \$PATH...\n"
+fi
+
+if ! [[ -x $HMMBUILD ]]; then
+        EXECUTABLE_ERROR=`echo "TRUE"`
+        printf "\nERROR: Cannot find hmmbuild executable in \$PATH...\n"
+fi
+
+if ! [[ -x $HMMPRESS ]]; then
+        EXECUTABLE_ERROR=`echo "TRUE"`
+        printf "\nERROR: Cannot find hmmpress executable in \$PATH...\n"
+fi
+
+if ! [[ -x $HMMSCAN ]]; then
+        EXECUTABLE_ERROR=`echo "TRUE"`
+        printf "\nERROR: Cannot find hmmscan executable in \$PATH...\n"
+fi
+
+if ! [[ -x $PULL_COORDINATES ]]; then
+        EXECUTABLE_ERROR=`echo "TRUE"`
+        printf "\nERROR: Cannot find Pull_coordinates.py executable in \$PATH...\n"
+fi
+
+if ! [[ -x $SELECT_CONTIGS ]]; then
+        EXECUTABLE_ERROR=`echo "TRUE"`
+        printf "\nERROR: Cannot find select_contigs.pl executable in \$PATH...\n"
+fi
+
+if ! [[ -x $BEST_FIT_DOMAINS ]]; then
+        EXECUTABLE_ERROR=`echo "TRUE"`
+        printf "\nERROR: Cannot find Best_fit_domains.py executable in \$PATH...\n"
+fi
+
+if ! type -p "python2.7" > /dev/null ; then
+        EXECUTABLE_ERROR=`echo "TRUE"`
+        printf "\nERROR: Cannot find python2.7 executable in \$PATH...\n"
+fi
+
+if ! python2.7 -c "import Bio" ; then
+	EXECUTABLE_ERROR=`echo "TRUE"`
+        printf "\nERROR: Cannot find BioPython package for Python2.7...\n"
+fi
+
+if ! type -p "python3" > /dev/null ; then
+	EXECUTABLE_ERROR=`echo "TRUE"`
+	printf "\nERROR: Cannot find python3 executable in \$PATH...\n"
+fi
+
+if [[ ${EXECUTABLE_ERROR} == "TRUE" ]]; then #If any program cannot be executed, exit
+        printf "Exiting...\n"
+        exit 1
+fi
 
 ######################################
 
