Fixed error introduced in Best_fit_domains.py Updating tiammat to allow users to spectify inclusion and reporting thresholds for the hmmer steps. Flags have been introduced, now must be implemented into the program. Changes will be made to the hmmscan and hmmsearch lines to introduce conditionals where if -I or -R are not default, a different permutation of these programs will be run along with a different version of Best_fit_domains.py for filtering. `

diff --git a/tiammat b/tiammat
--- a/tiammat
+++ b/tiammat
@@ -1,5 +1,18 @@
 #!/usr/bin/env bash
 
+#If no arguments are passed to tiammat, print help output
+if [[ "$#" == 0 ]]; then
+	printf "\n\t-d [directory]\tSpecify directory containing protein datasets [DEFAULT: pwd]\n"
+	printf "\t-h\t\tPrint help\n"
+	printf "\t-I [float]\tSpecify hmmscan/hmmsearch per-target and per-domain e-value inclusion thresholds (default: 0.01)\n"
+	printf "\t-m [directory]\tSpecify directory containing pfam models and seeds [MANDATORY; cannot be the same directory as datasets]\n"
+	printf "\t-o [string]\tSet name for output directory [default: TIAMMAt_output_{MONTH}_{DAY}_{YEAR}_{TIME}]\n"
+	printf "\t-p [path]\tSpecify path to Pfam database [MANDATORY]\n"
+	printf "\t-R [float]\tSpecify hmmscan/hmmsearch per-target and per-domain e-value reporting thresholds (default: 10.0)\n"
+	printf "\t-t [integer]\tSpecify number of threads for hmmscan and hmmsearch\n\n"
+	exit 1
+fi
+
 # LOADING PROGRAM PATHS AS VARIABLES #
 
 # Add Git folder to path
@@ -92,12 +105,14 @@ DATASET_DIR=`pwd`
 PFAM_DIR=`echo "NULL"`
 PFAM_DB_PATH=`echo "NULL"`
 THREADS=`echo "1"`
+REP_THRESH=`echo "DEFAULT"`
+INC_THRESH=`echo "DEFAULT"`
 
 ##################################
 
 # USER DEFINED VARIABLES #
 
-while getopts ":o:d:m:p:t:h" opt; do
+while getopts ":o:d:m:p:t:I:R:h" opt; do
 	case $opt in
 		o) # Set output directory name
 			OUTPUT_DIR=`echo "${OPTARG}"`
@@ -114,12 +129,20 @@ while getopts ":o:d:m:p:t:h" opt; do
 		t) # Set number of threads
 			THREADS=`echo "${OPTARG}"`
 			;;
+		I) # Set hmmscan and hmmsearch per-target and per-domain inclusion thresholds (default is 0.01)
+			INC_THRESH=`echo "${OPTARG}"`			
+			;;
+		R) # Set hmmscan and hmmsearch per-target and per-domain reporting thresholds (default is 10.0)
+			REP_THRESH=`echo "${OPTARG}"`
+			;;			
 		h) # Report help information
 			printf "\n\t-d [directory]\tSpecify directory containing protein datasets [DEFAULT: pwd]\n"
 			printf "\t-h\t\tPrint help\n"
+			printf "\t-I [float]\tSpecify hmmscan/hmmsearch per-target and per-domain e-value inclusion thresholds (default: 0.01)\n"
 			printf "\t-m [directory]\tSpecify directory containing pfam models and seeds [MANDATORY; cannot be the same directory as datasets]\n"
-			printf "\t-o [string]\tSet name for output directory [default: TIAMMAt_output_{DATE}]\n"
+			printf "\t-o [string]\tSet name for output directory [default: TIAMMAt_output_{MONTH}_{DAY}_{YEAR}_{TIME}]\n"
 			printf "\t-p [path]\tSpecify path to Pfam database [MANDATORY]\n"
+			printf "\t-R [float]\tSpecify hmmscan/hmmsearch per-target and per-domain e-value reporting thresholds (default: 10.0)\n"
 			printf "\t-t [integer]\tSpecify number of threads for hmmscan and hmmsearch\n\n"
 			exit 1
 			;;
@@ -133,6 +156,12 @@ while getopts ":o:d:m:p:t:h" opt; do
 			;;
 	esac
 done
+
+#if [[ ${REP_THRESH} != "DEFAULT" ]] || [[ ${INC_THRESH} != "DEFAULT" ]]; then
+#	echo "REPORTING THRESHOLD IS: ${REP_THRESH}"
+#	echo "INCLUSION THRESHOLD IS: ${INC_THRESH}"
+#	exit 1
+#fi
 
 ##########################
 
